# Generated by Django 5.2.7 on 2025-10-28 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_juego'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='user',
        ),
        migrations.CreateModel(
            name='ProgresoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('mejoras', models.JSONField(default=dict)),
                ('template_actual', models.CharField(default='juego.html', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
