# Generated by Django 5.2.7 on 2025-10-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_juego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='user',
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
