# Generated by Django 5.2.7 on 2025-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_juego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('costo', models.IntegerField(blank=True, default=0, null=True)),
                ('about', models.TextField(default=20)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('incremento', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='user',
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
