# Generated by Django 5.2.7 on 2025-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_progreso_user_progresojugador_delete_juego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresojugador',
            name='template_actual',
            field=models.CharField(default='game.html', max_length=100),
        ),
    ]
