# Generated by Django 5.2.7 on 2025-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_progresojugador_template_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresojugador',
            name='mejoras',
        ),
        migrations.AddField(
            model_name='progresojugador',
            name='click_power',
            field=models.IntegerField(default=1),
        ),
    ]
