# Generated by Django 5.2.7 on 2025-10-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progreso',
            old_name='botellas',
            new_name='costo',
        ),
        migrations.AddField(
            model_name='progreso',
            name='descripcion',
            field=models.TextField(default=20),
        ),
        migrations.AddField(
            model_name='progreso',
            name='incremento',
            field=models.IntegerField(default=0),
        ),
    ]
