# Generated by Django 5.2.7 on 2025-10-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_botellas_progreso_costo_progreso_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='user',
        ),
        migrations.AlterField(
            model_name='progreso',
            name='costo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='incremento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
