# Generated by Django 5.2.7 on 2025-10-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_progresojugador_mejoras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresojugador',
            name='mejoras_desbloqueadas',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='progresojugador',
            name='template_actual',
            field=models.CharField(default='game_1.html', max_length=100),
        ),
    ]
