# Generated by Django 5.2.7 on 2025-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_progresojugador_mejoras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=40, null=True)),
                ('costo', models.IntegerField(blank=True, default=0, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('incremento', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
