# Generated by Django 5.2.7 on 2025-10-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_progreso_user_alter_progreso_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='desbloqueables',
        ),
    ]
