# Generated by Django 5.2.7 on 2025-10-29 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='relUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.progresojugador'),
        ),
    ]
