# Generated by Django 5.2.7 on 2025-10-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_progresojugador_mejoras_desbloqueadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresojugador',
            name='template_actual',
            field=models.CharField(default='game.html', max_length=100),
        ),
    ]
