# Generated by Django 5.2.7 on 2025-10-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_progreso_desbloqueables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progreso',
            old_name='descripcion',
            new_name='about',
        ),
        migrations.AddField(
            model_name='progreso',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
