# Generated by Django 5.2.7 on 2025-10-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_items_relusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='relUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.progresojugador'),
        ),
    ]
