# Generated by Django 5.2.7 on 2025-11-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_items_relusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='bono',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='items',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='incremento',
            field=models.IntegerField(default=1),
        ),
    ]
