# Generated by Django 5.2.7 on 2025-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_items_bono_alter_items_cantidad_alter_items_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='incremento',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
    ]
